/**
 * Writes the compiled stylesheet into a module, so the shadow root can be
 * handed it as a string: a host app's bundler never has to know this package
 * carries CSS. The output is generated and gitignored.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync('.css-build/overlay.css', 'utf8');

writeFileSync(
  'src/styles/overlay-css.generated.ts',
  `// Generated by scripts/embed-css.mjs from src/styles/overlay.css. Do not edit.\nexport const OVERLAY_CSS: string = ${JSON.stringify(css)};\n`
);
